ficheros <- list.files()

for(i in 1:length(ficheros)){
entrada <- readLines(ficheros[i])
salida <- gsub("cͥ", "c＜r＞i`", entrada)
salida <- gsub("ã", "a＜n＞", salida)
salida <- gsub("ẽ", "e＜n＞", salida)
salida <- gsub("ĩ", "i＜n＞", salida)
salida <- gsub("õ", "o＜n＞", salida)
salida <- gsub("ũ", "u＜n＞", salida)
salida <- gsub("q̃", "q＜ue＞", salida)
salida <- gsub("om̃e", "om＜n＞e", salida)
salida <- gsub("ꝰ", "＜os＞", salida)
salida <- gsub("⁊", "&amp;", salida)
salida <- gsub("ͥ", "＜r＞i`", salida)
salida <- gsub("̾", "＜er＞", salida)
salida <- gsub("qͣ", "q＜u＞a`", salida)
salida <- gsub("ꝑa", "p＜ar＞a", salida)
salida <- gsub("ꝑ", "p＜or＞", salida)
salida <- gsub("tͣ", "t＜r＞a`", salida)
salida <- gsub("ç", "ç", salida)
salida <- gsub(" ꝯ", " c＜on＞", salida)
salida <- gsub("ꝯ ", "＜os＞ ", salida)
salida <- gsub("om̃s", "om＜ne＞s", salida)
salida <- gsub("qͥs", "q＜u＞i`s", salida)
salida <- gsub("õe", "o＜mn＞e", salida)
salida <- gsub("ꝓ", "p＜ro＞", salida)
salida <- gsub("m̃t", "m＜en＞t", salida)
salida <- gsub("õe", "o＜mn＞e", salida)
salida <- gsub("õs", "o＜mne＞s", salida)
salida <- gsub("głi", "gl＜es＞i", salida)
salida <- gsub("cłi", "cl＜er＞i", salida)
salida <- gsub("oẽ", "o＜mn＞e", salida)
salida <- gsub("cli", "cl＜er＞i", salida)
salida <- gsub("cłp", "c＜u＞lp", salida)
salida <- gsub("ꝑd", "p＜er＞d", salida)
salida <- gsub("q̈", "q＜u＞a`", salida)
salida <- gsub("ç", "ç", salida)
salida <- gsub("ñ", "ñ", salida)
salida <- gsub("ẜ", "s＜er＞", salida)
salida <- gsub("Qnͣ", "Q＜u＞a`n", salida)
salida <- gsub("qnͣd", "q＜u＞a`n", salida)
salida <- gsub("q̃r", "q＜u＞a`r", salida)
salida <- gsub("at̾", "at＜ur＞", salida)
salida <- gsub("pła", "pl＜anet＞a", salida)
salida <- gsub("tiẽp", "tie＜n＞p", salida)
#salida <- gsub("", "＜＞", salida)
salida <- gsub("ᷤ", "s`", salida)
salida <- gsub("ͦ", "o`", salida)
salida <- gsub("ͣ", "a`", salida)
writeLines(salida, ficheros[i])
}
